FROM node:14

WORKDIR /WORKERHOME

COPY ./worker/package.json ./worker/package.json
COPY ./libs/library/package.json ./libs/library/package.json

RUN cd ./libs/library && npm install
RUN cd ./worker && npm install
RUN npm install typescript -g

COPY ./libs/library ./libs/library
COPY ./worker ./worker


RUN cd worker && npm run build



CMD ["node", "./worker/dist/index.js"]